### ISSUE TITLE
Frontent issue

### ISSUE THREAD

**Issue by Krushna-Nanda** [sahoo2756/MERN-STACK-APP#4]
Upon logging in, the website should dynamically adjust its interface to reflect the user's authentication status. This means that the "Sign Up" and "Log In" buttons should be hidden once the user is authenticated. Instead, they could be replaced with options relevant to the logged-in user, such as a profile icon or a "Log Out" button.

Additionally, incorporating a dark and light theme changer enhances the user experience by allowing them to personalize the website's appearance according to their preferences. This feature can be implemented through a settings menu or toggle switch, enabling users to seamlessly switch between dark and light modes. The chosen theme should persist across sessions, ensuring consistency and convenience for the user.

**Comment by sahoo2756** [comment]
Ok thank you for your feedback , to our open source project . I think you intersted in debugging the code , can u join our team for more experience. Thank you for your feedback.

**Comment by Krushna-Nanda** [comment]
im happy to join
